# store current information before CLEAR_VARS

USER_LOCAL_MODULE:=$(LOCAL_MODULE)
USER_LOCAL_PATH:=$(LOCAL_PATH)
USER_LOCAL_C_INCLUDES:=$(LOCAL_C_INCLUDES)
USER_LCCAL_SRC_FILES:=$(LOCAL_SRC_FILES)
USER_LOCAL_CFLAGS:=$(LOCAL_CFLAGS)
USER_LOCAL_LDFLAGS:=$(LOCAL_LDFLAGS)
USER_LOCAL_STATIC_LIBRARIES:=$(LOCAL_STATIC_LIBRARIES)
USER_LOCAL_SHARED_LIBRARIES:=$(LOCAL_SHARED_LIBRARIES)
USER_LOCAL_LDLIBS:=$(LOCAL_LDLIBS)
USER_LOCAL_CPPFLAGS:=$(LOCAL_CPPFLAGS)

CURRENT_ABS_FOLDER_PATH=/$(patsubst /%,%,$(subst $($(abspath $(USER_LOCAL_PATH))),,$(abspath $1)))

THIS_LOCAL_ABS_PATH := $(call CURRENT_ABS_FOLDER_PATH, $(call my-dir))
LOCAL_PATH:=$(subst ?,,$(firstword ?$(subst \, ,$(subst /, , $(abspath $(call my-dir))))))

# settings of subfolder
include $(CLEAR_VARS)
include $(THIS_LOCAL_ABS_PATH)/aio/aio.mk
include $(THIS_LOCAL_ABS_PATH)/core/core.mk
include $(THIS_LOCAL_ABS_PATH)/devices/devices.mk
include $(THIS_LOCAL_ABS_PATH)/protocols/protocols.mk
include $(THIS_LOCAL_ABS_PATH)/transports/transports.mk
include $(THIS_LOCAL_ABS_PATH)/utils/utils.mk

SOURCE_HDR := $(LOCAL_C_INCLUDES)
SOURCE_SRC := $(LOCAL_SRC_FILES)

#restore the LOCAL_PATH
include $(CLEAR_VARS)
LOCAL_MODULE:=$(USER_LOCAL_MODULE)
LOCAL_PATH:=$(USER_LOCAL_PATH)
LOCAL_C_INCLUDES:=$(USER_LOCAL_C_INCLUDES)
LOCAL_SRC_FILES:=$(USER_LCCAL_SRC_FILES)
LOCAL_CFLAGS:=$(USER_LOCAL_CFLAGS)
LOCAL_LDFLAGS:=$(USER_LOCAL_LDFLAGS)
LOCAL_STATIC_LIBRARIES:=$(USER_LOCAL_STATIC_LIBRARIES)
LOCAL_SHARED_LIBRARIES:=$(USER_LOCAL_SHARED_LIBRARIES)
LOCAL_LDLIBS:=$(USER_LOCAL_LDLIBS)
LOCAL_CPPFLAGS:=$(USER_LOCAL_CPPFLAGS)
# append to user
LOCAL_C_INCLUDES += $(SOURCE_HDR)
LOCAL_SRC_FILES += $(SOURCE_SRC)

$(info LOCAL_MODULE: $(LOCAL_MODULE))
